apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    []
  mapUsers: |
    - userarn: arn:aws:iam::694226982622:user/Riten
      username: riten
      groups:
        - system:masters
