# k8s-manifest.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fsl-app
  namespace: production
spec:
  serviceName: fsl-app-service # Headless service for StatefulSet
  replicas: 3
  selector:
    matchLabels:
      app: fsl-app
  template:
    metadata:
      labels:
        app: fsl-app
    spec:
      containers:
        - name: fsl-app
          image: localhost:5000/fsl-challenge:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: fsl-app-service
  namespace: production
spec:
  clusterIP: None # Headless for StatefulSet
  selector:
    app: fsl-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service # LoadBalancer for external access
metadata:
  name: fsl-app-lb
  namespace: production
spec:
  type: LoadBalancer # NodePort/LoadBalancer; use NodePort if no LB
  selector:
    app: fsl-app
  ports:
    - port: 8080
      targetPort: 8080
